M48
; DRILL file {KiCad 9.0.7} date 2026-07-29T10:53:42+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-29T10:53:42+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.388
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.300
%
G90
G05
T1
X168.409Y-138.245
X191.548Y-138.245
T2
X171.63Y-52.53
X171.63Y-63.96
M30
